---
abstract: unknown
author:
  - 'Stig Sandbeck Mathisen <ssm@fnord.no>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-CachePurge
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '4.99'
version: '0.01'
